sciris/project.py

I've added (hopefully) the rest of the RPCs that will be needed that can go into `sciris/project.py`.  There are other RPCs that are being added and that will need to be added, but these must go in `hptool/main.py` for what we are currently doing with HealthPrior.

Finish project rpcs gc

---

.gitignore
README.md

@Situma this PR contains your changes to the readme file

merged instructions

---

sciris/core.py
sciris/corelib/asd.py

Copy over ASD from Atomica. The PR for optimization in Atomica now uses `sc.asd` and `asd.py` will be removed from the Atomica repo
Review and merge pls @cliffckerr

Add ASD routine

---

sciris/sc_version.py
scirisweb/sc_app.py
scirisweb/sc_objects.py
scirisweb/sc_user.py

Allows command line arguments to be passed to the server

Server cli

---

sciris/sc_fileio.py
sciris/sc_version.py
scirisweb/sc_app.py

Makes jsonification more robust

Jsonification

---

sciris/sc_fileio.py
scirisweb/sc_app.py

@RomeshA please review and check I didn't do anything silly :)

Troubleshoot jsonify

---

sciris/__init__.py
sciris/sc_parallel.py
sciris/sc_utils.py
tests/test_parallel.py
tests/test_utils.py
tests/testall.py

Adds some simple ways of accessing parallel functions -- namely sc.parallelize(), which can act like an alias to multiprocessing.Pool() or multiprocessing.Queue(); and sc.parallelcmd(), which is an experimental function that can parallelize pretty much anything, vaguely using Matlab-like parfor syntax. @RomeshA if you could take a quick look that'd be much appreciated!

Parallel tools

---

.travis.yml
tox.ini

Modify config to test against Python 2.7, 3.5, 3.6 and 3.7

Multi version testing

---

.travis.yml
sciris/sc_version.py

This PR updates the Travis config file so that PyPI will be updated whenever changes are merged into the master branch

Auto deploy

---

sciris/sc_dataframe.py
sciris/sc_fileio.py
sciris/sc_utils.py
sciris/sc_version.py

Subsumed by https://github.com/sciris/sciris/pull/63

Dataframe improvements

---

.travis.yml
README.md
sciris/sc_utils.py
sciris/sc_version.py
setup.py
tests/test_tox_utils.py

Add function to retrieve suggestions based on Levenshtein distance. How the user should be informed of suggestions is highly context dependent - therefore this function is primarily aimed at returning suggestions for the calling code to format and present as appropriate. The `die` argument results in a standard 'Did you mean' error being raised, for cases where sophisticated formatting and error handling is not required

Autosuggest

---

sciris/sc_utils.py
setup.py

Pre profiling

---

sciris/sc_fileio.py
sciris/sc_version.py

Last merge unintentionally broke saveobj()

Fix saveobj

---

sciris/sc_plotting.py
sciris/sc_version.py
tests/test_plotting.py

Add more color functions and tests

Add arrcolors

---

LICENSE
sciris/sc_dataframe.py
sciris/sc_fileio.py
sciris/sc_plotting.py
sciris/sc_utils.py
sciris/sc_version.py
setup.py
tests/test_fileio.py
tests/test_utils.py

Subsumes previous PR. Closes #82. Major changes:
* `dataframe` now works with a dict
* Additional utilities/aliases: `thisdir()` and `traceback()`
* More flexible JSON options
* Improved testing

Util updates

---

sciris/sc_dataframe.py
sciris/sc_fileio.py
sciris/sc_version.py

Allow a dataframe to be created from a dict

Dict dataframe input

---

sciris/sc_fileio.py
sciris/sc_utils.py
sciris/sc_version.py
tests/test_utils.py

Improves UUIDs and makes some other small fixes to utils

Small util updates

---

sciris/sc_fileio.py
sciris/sc_odict.py
sciris/sc_plotting.py
sciris/sc_utils.py
sciris/sc_version.py

Remove six

---

sciris/sc_utils.py
sciris/sc_version.py
tests/test_utils.py

Adds a small utility to merge two dictionaries

Add mergedicts()

---

CHANGELOG.md
CODE_OF_CONDUCT.md
sciris/sc_fileio.py
sciris/sc_utils.py
sciris/sc_version.py

Addresses issues with various utilities.
Closes #88, #95, #96, #97, #98, #99, #100

Utility updates

---

CHANGELOG.md
sciris/sc_utils.py
sciris/sc_version.py
tests/test_utils.py

This PR adds the `sc.search` function to search objects/dicts for attributes by name

Add search function

---

CHANGELOG.rst
sciris/sc_fileio.py
sciris/sc_math.py
sciris/sc_odict.py
sciris/sc_plotting.py
sciris/sc_utils.py
sciris/sc_version.py
setup.py
tests/check_coverage
tests/test_utils.py

Fixes various small issues, including a colormap registration causing an error with Matplotlib 3.4.0

Release 1.0.1

---

.github/workflows/tests.yaml
CHANGELOG.rst
sciris/sc_asd.py
sciris/sc_dataframe.py
sciris/sc_fileio.py
sciris/sc_math.py
sciris/sc_odict.py
sciris/sc_parallel.py
sciris/sc_plotting.py
sciris/sc_utils.py
sciris/sc_version.py
tests/.coveragerc
tests/README.rst
tests/check_coverage
tests/requirements_test.txt
tests/test_fileio.py
tests/test_math.py
tests/test_odict.py
tests/test_plotting.py
tests/test_utils.py

Release 1.1.0

---

sciris/sc_fileio.py
sciris/sc_version.py

Adds an ultra-robust unpickler that can, seriously, survive almost anything.

add universalfailed class

---

CHANGELOG.rst
sciris/sc_fileio.py
sciris/sc_version.py

Fix `TypeError: isinstance() arg 2 must be a type or tuple of types` which occurs because `None` is not the same as `NoneType` (and specifically `None` is not a type)

Fix type check

---

sciris/sc_datetime.py
sciris/sc_odict.py
sciris/sc_settings.py
sciris/sc_utils.py
tests/test_utils.py

Rc1.3.1 odict

---

CHANGELOG.rst
README.rst
docs/conf.py
sciris/sc_datetime.py
sciris/sc_fileio.py
sciris/sc_math.py
sciris/sc_nested.py
sciris/sc_utils.py
sciris/sc_version.py
setup.py
tests/test_utils.py

Preliminary PR doing housekeeping before merging feature branches into `develop`.

Initial v2.0.0 updates

---

sciris/sc_math.py
sciris/sc_plotting.py
tests/test_math.py

This PR implements function described in #280

Rc1.4.0 psl 280 numdigits

---

CHANGELOG.rst
sciris/sc_colors.py
sciris/sc_datetime.py
sciris/sc_fileio.py
sciris/sc_math.py
sciris/sc_nested.py
sciris/sc_parallel.py
sciris/sc_plotting.py
sciris/sc_printing.py
sciris/sc_utils.py
tests/test_math.py

This PR improves docstrings (#303)

Rc1.4.0 psl small fixes

---

CHANGELOG.rst
sciris/sc_math.py
tests/test_math.py

Rc1.4.0 psl 282 sanitize

---

CHANGELOG.rst
sciris/sc_fileio.py
tests/test_fileio.py

This PR includes an implementation of rmpath to remove files (os) and/or directories (shutil). Also includes updates to Spreadsheet method (readcells) so it works with `method='pandas'` (#289)

Rc1.4.0 psl rmpath and spreadsheet methods

---

.gitignore
CHANGELOG.rst
sciris/sc_datetime.py
sciris/sc_fileio.py
sciris/sc_math.py
sciris/sc_plotting.py
sciris/sc_utils.py
tests/test_fileio.py
tests/test_other.py

First batch of miscellaneous updates for rc2.0.0

rc2.0.0a updates

---

CHANGELOG.rst
LICENSE
sciris/sc_colors.py
sciris/sc_dataframe.py
sciris/sc_fileio.py
sciris/sc_math.py
sciris/sc_odict.py
sciris/sc_plotting.py
sciris/sc_profiling.py
sciris/sc_settings.py
sciris/sc_utils.py
sciris/sc_version.py
tests/test_dataframe.py
tests/test_fileio.py
tests/test_utils.py

Mostly bugfixes, see https://github.com/sciris/sciris/milestone/12

Version 2.0.1

---

sciris/sc_utils.py

Add kwargs to sc.runcommand

---

CHANGELOG.rst
sciris/sc_datetime.py
sciris/sc_fileio.py
sciris/sc_nested.py
sciris/sc_parallel.py
sciris/sc_printing.py
sciris/sc_utils.py
sciris/sc_version.py
tests/test_printing.py
tests/test_utils.py

Improves `sc.iterobj()` and `sc.prepr()`, and introduces `sc.quickobj()` and `sc.ifelse()`

Release 3.1.5

---

sciris/sc_asd.py

-Fix divide by zero
-Add minval arg and stop if absolute minimum reached
-Add warning for negative objective function vals
Closes #596

Improve handling of zero/negative objective function for ASD

---

CHANGELOG.rst
sciris/_extras/legacy.py
sciris/sc_asd.py
sciris/sc_colors.py
sciris/sc_dataframe.py
sciris/sc_datetime.py
sciris/sc_nested.py
sciris/sc_odict.py
sciris/sc_parallel.py
sciris/sc_plotting.py
sciris/sc_profiling.py
sciris/sc_utils.py
sciris/sc_version.py
sciris/sc_versioning.py
tests/files/make_archive.py
tests/sc_test_utils.py
tests/test_asd.py
tests/test_colors.py
tests/test_dataframe.py
tests/test_datetime.py
tests/test_fileio.py
tests/test_math.py
tests/test_nested.py
tests/test_odict.py
tests/test_parallel.py
tests/test_plotting.py
tests/test_printing.py
tests/test_utils.py
tests/test_versioning.py

Fixes to `sc.setnested()`, `sc.dataframe.insertrow()`, and the new `sc.counter` class.

Version 3.2.3
