- sciris/datastore.py
- sciris/project.py
I'm implemented changes in `datastore.py` and `project.py` to change the way uploading and downloading directories work.  These now use the `FileSaveDirectory` class defined in `datastore.py`.   This is capable of creating and temporary directories (which get erased, along with their contents when the web app is halted).  Note: To test this, you need the corresponding changes in the `hptool` repo.
> Uploads downloads temp dir gc

- sciris/corelib/utils.py
Minor fix for `gitinfo`, using `cd` doesn't work property on Windows, but `git` provides the `-C` flag to set the repository directory instead
> Fix cd behaviour on Windows

- sciris/weblib/datastore.py
- sciris/weblib/scirisobjects.py
- sciris/weblib/user.py
Improvements have been made to the `ScirisCollection` class.  Now, it is possible to determine whether the `ScirisObject`s in the collection are stored within the collection itself (which was the case before always), or whether the `ScirisObject`s are to be kept out in the `DataStore` and (UUID) pointers are just provided inside the collection to these entries.  The default setting is to not includes the objects inside the collection.  This is better to do, especially in cases where there are many entries in the collection or each entry is large in terms of its memory footprint.  Deletes and updates of entries in the collection are much, much faster under these circumstances.
> Redis slowness gc

- sciris/sc_utils.py
Use `LooseVersion` instead of custom logic
> Simpler version comparison based on built-in LooseVersion

- sciris/sc_plotting.py
The function to produce a separate legend can fail with error `Can not put single artist in more than one figure` for figures that contain certain artists (e.g. stacked line plots) even though it is OK for others (e.g. normal line plots). Fix as described [here](https://stackoverflow.com/questions/42072704/move-or-copy-patches-between-figures)
> Fixes for separate legends on stacked plots

- sciris/sc_utils.py
This add a simple class that wraps `tic` and `toc` to manage storing the start time and extra formatting for `toc`. For example
```
>>> timer = Timer()
>>> timer.toc()
Elapsed time: 2.63 s
>>> timer.toc()
Elapsed time: 5.00 s
```
The main reason for adding this is because the `__enter__` and `__exit__` methods allow this to be used as a one-line timing system in a `with-as` block e.g.
```
>>> with Timer(label='mylabel') as t:
>>>     foo()
```
which will print out the elapsed time when the block finishes
> Add simple timer class

- sciris/sc_utils.py
- sciris/sc_version.py
This adds a utility `sc.elapsed_time_str` based on https://gist.github.com/alexwlchan/73933442112f5ae431cc that gives a nice human-readable representation of time elapsed. It takes in a datetime, and then internally subtracts it from the current time and returns a human readable string, like
- 'just now'
- '5 minutes ago'
- 'yesterday'
This is a nicer way of displaying recent dates e.g. last modified times, when they have happened recently e.g.
> Add elapsed time function

- sciris/sc_fileio.py
This PR adds a 'blob' argument to the `Blobject` constructor. Currently, the `source` argument can take in a string, which is interpreted as a filename. However, users may be in possession of a binary array/string corresponding to the actual file content. They can create an empty `Blobject` and store that string in `Blobject.blob` but this involves an extra step and doesn't suit inline usage of classes like `Spreadsheet`. In theory it could be handled. The implementation uses a separate argument rather than adding an additional conditional to `source` depending on type - on Python 3 we can robustly check for 'str' vs 'bytes' but it's more complex in Python 2, plus explicitly naming the `blob` argument helps avoid any accidental use of the wrong option
> Add 'blob' argument to blobject

- sciris/sc_fileio.py
- sciris/sc_version.py
This PR makes it so that if no filename is specified, `saveobj` will return a `BytesIO` instance containing the gzipped data. The initial use case is for web apps to serve pickles (e.g. `.prj` files) from `BytesIO` streams rather than writing them to disk. 
@cliffckerr I thought it was a fairly clean implementation to have `filename=None` mean that you don't want to write a file to disk (rather than that resulting in `default.obj` being written) but I don't mind if you prefer something different, as long as the RPC can call `saveobj` and end up somehow with a `BytesIO`
> saveobj with no filename returns a BytesIO

- .travis.yml
- sciris/sc_fileio.py
- Path objects can now be used e.g.
```
from pathlib import Path
rootdir = Path("/foo/sciris")
x = sc.loadobj(rootdir/"test"/"myfile.obj")
```
- Attempting to load a file no longer results in creating missing directories (this would be an expected side-effect when saving, but not when loading
> Save load changes

- sciris/sc_fileio.py
The original code had an execution path leading to `obj` being undefined (if the `exec` succeeded but didn't create the variable for whatever reason). However, it seems that at least some of the cases caught by `exec` can instead be handled by using `importlib` rather than just calling `__import__` - this then simplifies the logic where any failure at that point results in `makefailed` being used.
It also wasn't easy to see how to pass `verbose=True` into `find_class` so this PR also changes it to default to `True` so that errors can be identified. This would make bulk imports more noisy (but they're generally scripted anyway) but being verbose is very useful for diagnosing objects with issues
> Change logic

- sciris/sc_utils.py
This PR aims to extend `profile()` by allowing arguments to be passed to the `run` function, which would remove the need to wrap simple function calls. It also removes several layers of wrappers which should make the output of `profile()` cleaner in simple cases
> Profile changes

- sciris/sc_plotting.py
- sciris/sc_version.py
Some small fixes to colormaps; specifically fixing registration for bicolormap and also allowing the syntax `sc.parualcolormap(apply=True)` to activate it immediately (equivalent to `pl.set_cmap('parula')`).
> Colormap updates

- sciris/sc_fileio.py
`sc.loadobj` supports passing in `Path` objects from pathlib - this PR extends this to other IO routines. This is most useful for `sc.Spreadsheet` which gains this functionality via `Blobject.load()`
> Support Paths in makefilepath and blobject loading

- CHANGELOG.md
- sciris/sc_fileio.py
- sciris/sc_utils.py
- sciris/sc_version.py
The main change is that `Blobject.save` had defaults specific to spreadsheets, which are better specified in `Spreadsheet.save` since `Blobject` instances could be storing any time of binary content. This refactored implementation then leverages the existing functionality in `makefilepath` to ensure that `Spreadsheet` files end in `.xlsx` as well as allowing users to pass in a `Path` instance as the filename
> Default filename

- CHANGELOG.md
- sciris/sc_parallel.py
- sciris/sc_version.py
Stumbled onto this subtle issue with parallelization. It looks very much like if a mutable object is passed in as an argument, at least inside `kwargs`, under *some* circumstances it is possible that a worker process will reuse the same object in memory. It doesn't happen in an obviously predictable way with regard to the inputs e.g. if I have 4 CPUs, doing 4, 8, or even 12 tasks is fine, but the issue reproducibly happens when using >20 tasks, at least on my 4 core machine. This example is modelled after `covasim.MultiSim`:
```
import sciris as sc
import numpy as np
class Foo():
def __init__(self):
self.x = 0
def add(self,x):
self.x += x
def add(obj,val):
obj.add(val)
return obj
if __name__ == '__main__':
n_runs = 4
test_obj = Foo()
iterkwargs = {'val': np.arange(n_runs)}
kwargs = …
```
> Fix shared object bug in parallization

- CHANGELOG.md
- sciris/sc_utils.py
- sciris/sc_version.py
- tests/test_utils.py
Class instances might not have a `__dict__` defined if the class uses `__slots__` instead, which causes an infinite recursion in `prepr()` if such an object is encountered. This PR modifies `prepr()` to use `__slots__` for such classes
> Fix prepr() for __slots__

- sciris/sc_fileio.py
This PR adds a `__getstate__` implementation to `sc.Spreadsheet` to drop the workbook cache when serializing (e.g., when using dcp or saveobj). If the cached workbook is not discarded, these operations become much slower because the content of the file is being duplicated in a heavy container. This is particularly problematic when operating on larger spreadsheets. For example
```
import sciris as sc
with sc.Timer('create spreadsheet'):
ss = sc.Spreadsheet('iicf_mnch_20200121_v1.xlsx')
with sc.Timer('save blob1'):
sc.saveobj('test1',ss)
with sc.Timer('open wb'):
ss.openpyxl()
with sc.Timer('dcp'):
sc.dcp(ss)
with sc.Timer('save blob2'):
sc.saveobj('test2',ss)
```
With a 6mb spreadsheet, without dropping the cache, the timings are
```
create spreadsheet: 0.00300 s
save blob1: 0.205 s
open …
```
> Drop cache

- sciris/sc_colors.py
- tests/test_datetime.py
- tests/test_profiling.py
Revert Matplotlib change, which is a deprecation in 3.6.1, but the alternative is an error in previous versions.
> Revert Matplotlib change

- CHANGELOG.rst
- sciris/sc_fileio.py
- sciris/sc_version.py
`sc.save()` supports passing in `filename=None` to create the file in-memory as a file stream. However, the existing logic results in the filename being re-populated with the default value, preventing the `io.BytesIO` pathway from being used. This PR refactors the logic for input validation to correct this.
Also, it looked like previously if the filename could not be validated, an error message was defined, but it would not be raised. An exception is now raised once the error message is defined
> Fix filename=None behaviour

- docs/tutorials/tut_files.ipynb
extra `]` was breaking markdown link.
> DOC: fix link markup

- sciris/sc_dataframe.py
If the user passes both cols and columns to dataframe init columns was silently ignored.
> FIX: do not ignore user input in dataframe init

- tests/README.rst
It is very surprising to me that invoking `pytest` from the top of the repo fails but invoking it from inside of the test directory works.
> FIX: correct invocation of deps installation in tests README.rst

- sciris/sc_datetime.py
Previously, timedsleep printed the “Sleeping for...” text after sleeping when called with verbose=True. Now, the message is printed before sleeping, as it should be.
Fixes #526
> Fix timedsleep verbose=True timing

- sciris/sc_parallel.py
There is no need to return an exception of the same type as the original exception. We can return our own exception, and it will be clear which exception it originates from, because we're using `from`, causing the original exception to also be printed.
Fixes #527
> Fix sc.download HTML error handling

- sciris/sc_asd.py
Hi @cliffckerr 
Small bug in the verbose printing: the correct final function value is at `fvals[count]` both when we converge or stop early and when it reaches maxiters
I fixed this in `optima` already in https://github.com/optimamodel/optima/commit/5e027ea22808652a648f9bcd374919467ea51bde
Should be easy enough to go into 3.1.3?
I'm not sure why there is a change in the diff at the bottom of the file - I didn't change anything there... Feel free to do the change yourself on your end.
Thanks!
> Fix sc_asd.py final print of `best` and `ratio`

- sciris/sc_parallel.py
Hi @cliffckerr 
I think this should fix https://github.com/sciris/sciris/issues/557 if the intended behaviour is that if `kwargs` and `iterkwargs` share keys, then `iterkwargs` overrides `kwargs`?
Let me know what you think, and feel free to push commits to this branch
Thanks,
Kelvin
> Fix https://github.com/sciris/sciris/issues/557 by merging dictionaries into a new kwargs for each task

- sciris/sc_odict.py
Tiny change so that subclasses of `objdict` (e.g., `ndict`) print their actual class name rather than always printing `objdict`
> Set class name correctly for derived classes e.g., ndict

- sciris/__init__.py
This PR has an example fix for a migration error we're getting in Atomica. The issue seems to be that `prettyobj` was moved from `sc_utils` to `sc_printing` so when unpickling, the class can't be found. I've implemented one possible fix in this PR (this is the approach Atomica uses, except those mappings are in `migration.py` rather than `__init__.py` - there's no direct analogue of that in Sciris). But there's a ton of different ways to do it, so happy for you to do something different!
```
Traceback (most recent call last):
File "/Users/romesh.abeysuriya/miniconda3/envs/atomica311/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-2-201782cde910>", line 1, in <module> …
```
> Implement fix

- sciris/sc_nested.py
[Fix IterObj clearing skip argument if it is a dict, so you can reuse it](https://github.com/kelvinburke/sciris/commit/f57c83a420040a390f0f3bd5b08dd5137067439d)
^^ This fixes a bug: When doing `sc.equal(A, B, skip={'ids':['id1']})` the `skip` kwarg gets correctly passed to iterate over `A` but this clears the dictionary because `skip_ids = scu.tolist(skip.pop('ids', None))` , so the `skip` dictionary is now empty to iterate over `B`.
The fix is just to do `skip = scu.dcp(skip)`
[IterObj add skip_keys](https://github.com/kelvinburke/sciris/commit/c99d58ff515a77b343cd1c445a9fb2cd5535a23c)
Simple enhancement - allows skipping over keys, these can be generic eg. 
`skip={'keys':[0]}` allows skipping over the 0th object in arrays, lists and tuples.
[Add set_to_obj() (based off …
> 3 changes to sc.nested

- sciris/sc_math.py
- sciris/sc_plotting.py
Allow findnearest to work with other non-number scalar objects (e.g., ss.Date) that implement the requisite operators but otherwise return False for `isnumber()`
> Findnearest tweak

- sciris/sc_plotting.py
matplotlib 3.10 now checks `._parent_figure` when setting `.figure` so it's necessary to set the parent figure to `None` before trying to set the `figure` to `None`
> Fix for matplotlib 3.10

- sciris/sc_datetime.py
- The main change is for `datetoyear` to support `pd.Timestamp` which in turn allows it to support `starsim.date` instances
- This PR also proposes splitting `datetoyear(reverse=True)` into `yeartodate`, there isn't much overlap in code and it can be confusing that the function `datetoyear` might not in fact convert a date to a year!
> Split datetoyear and yeartodate, support pd.Timestamp
